name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: 'ProstaGra' 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./TauGame/TauGame.sln
    - name: Build
      run: dotnet build --no-restore ./TauGame/TauGame.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal ./TauGame/TauGame.sln
